GardeX/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.HomeApp.urls"))
]

apps/HomeApp/urls.py
from django.urls import path
from apps.HomeApp import views
app_name="HomeApp"
urlpatterns=[
    path("",views.HomeView.as_view(),name="HomeView"),
    path("about/",views.AboutMeView.as_view(),name="about"),
    path("credentials/",views.MoreInformationView.as_view(),name="credentials"),
    path("work/",views.WorksView.as_view(),name="work"),
    path("contact/",views.ContactView.as_view(),name="contact"),
    path("work-detail/",views.WorkDetail.as_view(),name="work-detail")

]

apps/HomeApp/models.py
from django.db import models

# Create your models here.

apps/HomeApp/views.py
from django.shortcuts import render
from django.views.generic import View,DetailView


class HomeView(View):

    def get(self,request):


        return render(request,"HomeApp/index.html")


class AboutMeView(View):

    def get(self,request):

        return render(request,"HomeApp/about.html")


class MoreInformationView(View):

    def get(self,request):

        return render(request,"HomeApp/credentials.html")


class WorksView(View):

    def get(self,request):


        return render(request,"HomeApp/works.html")



class ContactView(View):


    def get(self,request):

        return render(request,"HomeApp/contact.html")


class WorkDetail(View):

    def get(self,request):

        return render(request,"HomeApp/work-details.html")

apps/HomeApp/templates/HomeApp/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
        <!-- About -->
        <section class="about-area">
            <div class="container">
                <div class="d-flex about-me-wrap align-items-start gap-24">
                    <div data-aos="zoom-in">
                        <div class="about-image-box shadow-box">
                            <img src="{% static "assets/images/bg1.png" %}" alt="BG" class="bg-img">
                            <div class="image-inner">
                                <img src="{% static "assets/images/me2.png" %}" alt="About Me">
                            </div>
                        </div>
                    </div>

                    <div class="about-details" data-aos="zoom-in">
                        <h1 class="section-heading" data-aos="fade-up"><img src="{% static "assets/images/star-2.png" %}" alt="Star"> خود خلاصه <img src="assets/images/star-2.png" alt="Star"></h1>
                        <div class="about-details-inner shadow-box">
                            <img src="{% static "assets/images/icon2.png" %}" alt="Star">
                            <h1>دیوید هندرسون</h1>
                            <p>من یک طراح محصول مستقر در سانفرانسیسکو با تمرکز بر طراحی وب، تصویرسازی، توسعه بصری هستم. من طیف متنوعی از تجربیات را دارم که در زمینه ها و صنایع مختلف کار کرده ام.</p>
                        </div>

                    </div>
                </div>

                <div class="row mt-24">
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="about-edc-exp about-experience shadow-box">
                            <img src="{% static "assets/images/bg1.png" %}" alt="BG" class="bg-img">
                            <h3>تجربه</h3>

                            <ul>
                                <li>
                                    <p class="date">1400 -1402</p>
                                    <h2>طراح و توسعه دهنده فارمر</h2>
                                    <p class="type">طرح های بلو بیس</p>
                                </li>
                                <li>
                                    <p class="date">1400 -1402</p>
                                    <h2>توسعه دهنده فرانت اند</h2>
                                    <p class="type">لارسن و توبرو</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="about-edc-exp about-education shadow-box">
                            <img src="{% static "assets/images/bg1.png" %}" alt="BG" class="bg-img">
                            <h3>تحصیلات</h3>

                            <ul>
                                <li>
                                    <p class="date">1400 -1402</p>
                                    <h2>لیسانس روانشناسی</h2>
                                    <p class="type">دانشگاه کالیفرنیا</p>
                                </li>
                                <li>
                                    <p class="date">1400 -1402</p>
                                    <h2>کارشناسی ارشد طراحی</h2>
                                    <p class="type">دانشگاه تگزاس</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row mt-24">
                    <div class="col-md-12">
                        <div class="d-flex profile-contact-credentials-wrap gap-24">

                            <div data-aos="zoom-in">
                                <div class="about-profile-box info-box shadow-box h-full">
                                    <img src="{% static "assets/images/bg1.png" %}" alt="BG" class="bg-img">
                                    <div class="inner-profile-icons shadow-box">
                                        <a href="about.html#">
                                            <i class="iconoir-dribbble"></i>
                                        </a>
                                        <a href="about.html#">
                                            <i class="iconoir-twitter"></i>
                                        </a>
                                    </div>
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div class="infos">
                                            <h4>با من بمان</h4>
                                            <h1>پروفایل ها</h1>
                                        </div>
    
                                        <a href="contact.html" class="about-btn">
                                            <img id="rdt" src="{% static "assets/images/icon.svg" %}" alt="Button">
                                        </a>
    
                                    </div>
                                </div>
                            </div>

                            <div data-aos="zoom-in" class="flex-1">
                                <div class="about-contact-box info-box shadow-box">
                                    <a class="overlay-link" href="contact.html"></a>
                                    <img src="{% static "assets/images/bg1.png" %}" alt="BG" class="bg-img">
                                    <img src="{% static "assets/images/icon2.png" %}" alt="Icon" class="star-icon">
                                    <h1>بیایید <br>با هم <span>کار کنیم.</span></h1>
                                    <a href="contact.html" class="about-btn">
                                        <img id="rdt" src="{% static "assets/images/icon.svg" %}" alt="Button">
                                    </a>
                                </div>
                            </div>

                            <div data-aos="zoom-in" class="h-full">
                                <div class="about-crenditials-box info-box shadow-box">
                                    <a class="overlay-link" href="credentials.html"></a>
                                    <img src="{% static "assets/images/bg1.png" %}" alt="BG" class="bg-img">
                                    <img src="{% static "assets/images/sign.png" %}" alt="Sign">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div class="infos">
                                            <h4>بیشتر در مورد من</h4>
                                            <h1>اعتبارنامه</h1>
                                        </div>
    
                                        <a href="credentials.html" class="about-btn">
                                            <img id="rdt" src={% static "assets/images/icon.svg" %} alt="Button">
                                        </a>
    
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

apps/HomeApp/templates/HomeApp/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}

        <!-- Contact -->
        <section class="contact-area">
            <div class="container">
                <div class="gx-row d-flex justify-content-between gap-24">
                    <div class="contact-infos">
                        <h3 data-aos="fade-up">اطلاعات تماس</h3>
                        <ul class="contact-details">
                            <li class="d-flex align-items-center" data-aos="zoom-in">
                                <div class="icon-box shadow-box">
                                    <i class="iconoir-mail"></i>
                                </div>
                                <div class="right">
                                    <span>به ما ایمیل بزنید</span>
                                    <h4>info@bluebase.com</h4>
                                    <h4>info@bluebase2.com</h4>
                                </div>
                            </li>

                            <li class="d-flex align-items-center" data-aos="zoom-in">
                                <div class="icon-box shadow-box">
                                    <i class="iconoir-phone"></i>
                                </div>
                                <div class="right">
                                    <span>با ما تماس بگیرید</span>
                                    <h4>+1 504-899-8221</h4>
                                    <h4>+1 504-749-5456</h4>
                                </div>
                            </li>

                            <li class="d-flex align-items-center" data-aos="zoom-in">
                                <div class="icon-box shadow-box">
                                    <i class="iconoir-pin-alt"></i>
                                </div>
                                <div class="right">
                                    <span>لوکیشن</span>
                                    <h4>خیابان بیکر 22، تگزاس <br>ایالات متحده<br>W1U 3BW</h4>
                                </div>
                            </li>
                        </ul>

                        <h3 data-aos="fade-up">اطلاعات اجتماعی</h3>
                        <ul class="social-links d-flex align-center" data-aos="zoom-in">
                            <li><a class="shadow-box" href="contact.html"><i class="iconoir-dribbble"></i></a></li>
                            <li><a class="shadow-box" href="contact.html"><i class="iconoir-twitter"></i></a></li>
                            <li><a class="shadow-box" href="contact.html"><i class="iconoir-instagram"></i></a></li>
                        </ul>
                    </div>

                    <div data-aos="zoom-in" class="contact-form">
                        <div class="shadow-box">
                            <img src="assets/images/bg1.png" alt="BG" class="bg-img">
                            <img id="rtlsm" src="assets/images/icon3.png" alt="Icon">
                            <h1>بیا کار کنیم <span>با یکدیگر.</span></h1>
                            <form method="POST" action="https://wpriverthemes.com/landing/gridx-html/mailer.php">
                                <div class="alert alert-success messenger-box-contact__msg" style="display: none" role="alert">
                                    پیام شما با موفقیت ارسال شد.
                                </div>
                                <div class="input-group">
                                    <input type="text" name="full-name" id="full-name" placeholder="نام *">
                                </div>
                                <div class="input-group">
                                    <input type="email" name="email" id="email" placeholder="ایمیل *">
                                </div>
                                <div class="input-group">
                                    <input type="text" name="subject" id="subject" placeholder="عنوان شما *">
                                </div>
                                <div class="input-group">
                                    <textarea name="message" id="message" placeholder="پیام شما *"></textarea>
                                </div>
                                <div class="input-group">
                                    <button class="theme-btn submit-btn" name="submit" type="submit">ارسال پیام</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    
                </div>
            </div>
        </section>

{% endblock %}

apps/HomeApp/templates/HomeApp/credentials.html
{% extends "base.html" %}
{% load static %}
{% block content %}
        <!-- Credentials -->
        <section class="credential-area">
            <div class="container">
                <div class="gx-row d-flex">
                    <div class="credential-sidebar-wrap" data-aos="zoom-in">
                        <div class="credential-sidebar text-center">
                            <div class="shadow-box">
                                <img src="{% static "assets/images/bg1.png" %}" alt="BG" class="bg-img">
                                <div class="img-box">
                                    <img src="{% static "assets/images/me.png" %}" alt="درمورد من">
                                </div>
                                <h2>دیوید هندرسون</h2>
                                <p>@davidhenderson</p>
        
                                <ul class="social-links d-flex justify-content-center">
                                    <li><a href="credentials.html#"><i class="iconoir-dribbble"></i></a></li>
                                    <li><a href="credentials.html#"><i class="iconoir-twitter"></i></a></li>
                                    <li><a href="credentials.html#"><i class="iconoir-instagram"></i></a></li>
                                    <li><a href="credentials.html#"><i class="iconoir-facebook-tag"></i></a></li>
                                </ul>
        
                                <a href="contact.html" class="theme-btn">با من تماس بگیر</a>
                            </div>
                        </div>
                    </div>

                    <div class="credential-content flex-1">
                        <div class="credential-about" data-aos="zoom-in">
                            <h2>درمورد من</h2>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز</p>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                        </div>

                        <div class="credential-edc-exp credential-experience">
                            <h2 data-aos="fade-up">تجربیات</h2>
                            <div class="credential-edc-exp-item" data-aos="zoom-in">
                                <h4>1401 - 1402</h4>
                                <h3>طراح و توسعه دهنده فارمر</h3>
                                <h5>طرح های بلوبیس</h5>
                                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز</p>
                            </div>
                            <div class="credential-edc-exp-item" data-aos="zoom-in">
                                <h4>2017 - 2023</h4>
                                <h3>توسعه دهنده فرانت اند</h3>
                                <h5>لارسن و توبرو</h5>
                                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز</p>
                            </div>
                        </div>

                        <div class="credential-edc-exp credential-education">
                            <h2 data-aos="fade-up">تحصیلات</h2>
                            <div class="credential-edc-exp-item" data-aos="zoom-in">
                                <h4>1401 - 1402</h4>
                                <h3>لیسانس روانشناسی</h3>
                                <h5>دانشگاه کالیفرنیا</h5>
                                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز</p>
                            </div>
                            <div class="credential-edc-exp-item" data-aos="zoom-in">
                                <h4>1401 - 1402</h4>
                                <h3>کارشناسی ارشد طراحی</h3>
                                <h5>دانشگاه تگزاس</h5>
                                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز</p>
                            </div>
                        </div>

                        <div class="skills-wrap">
                            <h2 data-aos="fade-up">مهارت ها</h2>
                            <div class="d-grid skill-items gap-24 flex-wrap">
                                <div class="skill-item" data-aos="zoom-in">
                                    <span class="percent">85%</span>
                                    <h3 class="name">جاوا اسکریپت</h3>
                                    <p>زیرا وجود ندارد</p>
                                </div>
                                <div class="skill-item" data-aos="zoom-in">
                                    <span class="percent">78%</span>
                                    <h3 class="name">پایتون</h3>
                                    <p>زیرا وجود ندارد</p>
                                </div>
                                <div class="skill-item" data-aos="zoom-in">
                                    <span class="percent">92%</span>
                                    <h3 class="name">فیگما</h3>
                                    <p>زیرا وجود ندارد</p>
                                </div>
                                <div class="skill-item" data-aos="zoom-in">
                                    <span class="percent">90%</span>
                                    <h3 class="name">وردپرس</h3>
                                    <p>زیرا وجود ندارد</p>
                                </div>
                                <div class="skill-item" data-aos="zoom-in">
                                    <span class="percent">81%</span>
                                    <h3 class="name">ری اکت</h3>
                                    <p>زیرا وجود ندارد</p>
                                </div>
                                <div class="skill-item" data-aos="zoom-in">
                                    <span class="percent">87%</span>
                                    <h3 class="name">Adobe XD</h3>
                                    <p>زیرا وجود ندارد</p>
                                </div>

                            </div>
                        </div>

                        <div class="skills-wrap awards-wrap">
                            <h2 data-aos="fade-up">جوایز</h2>
                            <div class="d-grid skill-items gap-24 flex-wrap">
                                <div class="skill-item" data-aos="zoom-in">
                                    <span class="percent">14 مهر 1401</span>
                                    <h3 class="name">بلوبیس</h3>
                                    <p>زیرا وجود ندارد</p>
                                </div>
                                <div class="skill-item" data-aos="zoom-in">
                                    <span class="percent">13 آبان 1402</span>
                                    <h3 class="name">دمبله</h3>
                                    <p>زیرا وجود ندارد</p>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        


       {% endblock %}

apps/HomeApp/templates/HomeApp/work-details.html
{% extends "base.html" %}
{% load static %}
{% block content %}

        <!-- Breadcrumb -->
        <section class="breadcrumb-area">
            <div class="container">
                <div class="breadcrumb-content" data-aos="fade-up">
                    <p>برندینگ - استدیو ریون</p>
                    <h1 class="section-heading"><img src="{% static "assets/images/star-2.png" %}" alt="Star"> طراحی زیبایی برای برند <br>استارت آپ جدید <img src="assets/images/star-2.png" alt="Star"></h1>
                </div>
            </div>
        </section>

        <!-- Project Details -->
        <section class="project-details-wrap">
            <div class="project-details-img" data-aos="zoom-in">
                <img src="{% static "assets/images/project-dt-1.jpeg" %}" alt="Project Details">
            </div>

            <div class="container">
                <div data-aos="zoom-in">
                    <div class="d-flex project-infos-wrap shadow-box mb-24">
                        <img src="{% static "assets/images/bg1.png" %}" alt="BG" class="bg-img">
                        <img src="{% static "assets/images/icon2.png" %}" alt="Icon">
                        <div class="project-details-info flex-1">
                            <h3>استودیو ریون</h3>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز</p>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                        </div>
    
                        <div class="project-details-info flex-1">
                            <h3>درباره</h3>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز</p>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                        </div>
                    </div>
                </div>

                <div class="project-details-2-img mb-24" data-aos="zoom-in">
                    <img src="{% static "assets/images/project-dt-1.jpeg" %}" alt="Project">
                </div>

                <div class="row mb-24">
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="project-details-3-img">
                            <img src="{% static "assets/images/project3.jpeg" %}" alt="Project">
                        </div>
                    </div>
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="project-details-3-img">
                            <img src="{% static "assets/images/project4.jpeg" %}" alt="Project">
                        </div>
                    </div>
                </div>

                <div class="row mb-24">
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="project-details-3-img">
                            <img src="{% static "assets/images/project5.jpeg" %}" alt="Project">
                        </div>
                    </div>
                    <div class="col-md-6" data-aos="zoom-in">
                        <div class="project-details-3-img">
                            <img src="{% static "assets/images/project6.jpeg" %}" alt="Project">
                        </div>
                    </div>
                </div>

                <div data-aos="zoom-in">
                    <div class="project-about-2 d-flex shadow-box mb-24">
                        <img src="{% static "assets/images/bg1.png" %}" alt="BG" class="bg-img">
                        <div class="left-details">
                            <img src="{% static "assets/images/icon3.png" %}" alt="Icon">
                            <ul>
                                <li>
                                    <p>سال</p>
                                    <h4>2023</h4>
                                </li>
                                <li>
                                    <p>مشتری</p>
                                    <h4>استودیو ریون</h4>
                                </li>
                                <li>
                                    <p>خدمات</p>
                                    <h4>طراحی وب سایت</h4>
                                </li>
                                <li>
                                    <p>پروژه</p>
                                    <h4>پویا</h4>
                                </li>
                            </ul>
                        </div>
                        <div class="right-details">
                            <h3>شرح</h3>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز</p>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="project-details-img" data-aos="zoom-in">
                <img src="{% static "assets/images/project-dt-1.jpeg" %}" alt="Project Details">
            </div>

            <div class="container d-flex align-items-center justify-content-center" data-aos="zoom-in">
                <a href="work-details.html#" class="big-btn shadow-box">
                    پروژه بعدی
                </a>
            </div>
            
        </section>
        
        


        {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa_IR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>وبسایت شخصی مهدی رمضانی</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css">

    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/aos.css" %}">

    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
</head>
<body>

    <main class="main-homepage">

        <!-- Header -->
        <header class="header-area">
            <div class="container">
                <div class="gx-row d-flex align-items-center justify-content-between">
                    <a href="{% url "HomeApp:HomeView" %}" class="logo">
                        <img src="{% static "assets/images/logo.svg" %}" alt="Logo">
                    </a>

                    <nav class="navbar">
                        <ul class="menu">
                            <li class="active"><a href="{% url "HomeApp:HomeView" %}">خانه</a></li>
                            <li><a href="{% url "HomeApp:about" %}">درباره من</a></li>
                            <li><a href="{% url "HomeApp:work" %}">کارهای من</a></li>
                            <li><a href="{% url "HomeApp:contact" %}">تماس با من</a></li>
                        </ul>
                        <a href="contact.html" class="theme-btn">بیا حرف بزنیم</a>
                    </nav>

                    <a href="{% url "HomeApp:contact" %}" class="theme-btn">بیا حرف بزنیم</a>

                    <div class="show-menu">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
            </div>
        </header>

        {% block content %}

        {% endblock %}

    <footer class="footer-area">
            <div class="container">
                <div class="footer-content text-center">
                    <a href="index.html" class="logo">
                        <img src="{% static "assets/images/logo.svg" %}" alt="Logo">
                    </a>
                    <ul class="footer-menu">
                        <li><a href="{% url "HomeApp:HomeView" %}">خانه</a></li>
                        <li><a href="{% url "HomeApp:about" %}">درباره</a></li>
                        <li><a href="{% url "HomeApp:work" %}">کارها</a></li>
                        <li><a href="{% url "HomeApp:contact" %}">تماس با ما</a></li>
                    </ul>
                    <p class="copyright">
                        &copy; کلیه حقوق این سایت متعلق به <span>مهدی رمضانی</span>
                    </p>
                </div>
            </div>
        </footer>

    </main>


    <script src="{% static "assets/js/jquery-3.6.4.js" %}"></script>
    <script src="{% static "assets/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "assets/js/aos.js" %}"></script>
    <script src="{% static "assets/js/main.js" %}"></script>
</body>
</html>